### ISSUE TITLE
No implementation found for method launch app/checkAvailability

### ISSUE THREAD

**Issue by ukeOnFire** [pichillilorenzo/flutter_appavailability#8]
hi @pichillilorenzo 
I have just started to make an app iOS compatible and it seems that what has worked fine on Android is causing problems on iOS. 

I tried to check the app 'calshow://', here's the exception for one of the calls:

```
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
<asynchronous suspension>
#1      AppAvailability.checkAvailability (package:flutter_appavailability/flutter_appavailability.dart:38:42)
```

Thanks for your work, it's amazingly smooth on Android!

**Comment by pankti16** [comment]
Use a try-catch block:
```
try{
      print(await AppAvailability.checkAvailability(Platform.isIOS ? "youtube://" : "com.google.android.youtube"));
      AppAvailability.launchApp(Platform.isIOS ? "youtube://" : "com.google.android.youtube").then((_) 
      {
          print("App launched!");
      }).catchError((err) {
           Scaffold.of(context).showSnackBar(SnackBar(
               content: Text("App not found!")
           ));
          print(err);
       });
     }
     catch(ex)
     { 
        print(ex);
        Scaffold.of(context).showSnackBar(SnackBar(
                        content: Text("App not found!")
                    ));
     }
```
